

const datas = {
		  labels: {
		    code: "CB_20210208_001",
		    name: "name",
		    version: "C.1",
		    devType: "양산",
		    projectType: "PSO",
		    templateName: "PSO 프로젝트 템플릿",
		    purpose: "차량",
		    customer: "현대자동차",
		    endItem: "HYDROGEN TANK COMPLETE",
		    creator: "김규범",
		    createDate: "2021/01/02",
		    modifyDate: "2021/01/02",
		    pm: "김규범",
		    sales: "이석진",
		    design01: "김희천",
		    design02: "류수한",
		    manufacture: "",
		    production: "",
		    quality: "",
		    development: "",
		    management: "",
		    interal: "700",
		    cust: "0",
		    warranty: "warranty",
		    kotool: "",
		    ppap: "",
		    firstSOP: "",
		  },
		  charts: [
		    {
		      title: "Total net capex (k currency)",
		      values: [
		        { id: 1, value: 7000, label: "1" },
		        { id: 2, value: 4000, label: "2" },
		        { id: 3, value: 5000, label: "3" },
		        { id: 4, value: 5000, label: "4" },
		        { id: 5, value: 5000, label: "5" },
		      ],
		      ystart: 0,
		      yend: 10000,
		      ystep: 2000,
		      target: 9000,
		      target_color: "#ED0000",
		      plot: 50,
		    },
		    {
		      title: "Material margin / tank",
		      values: [
		        { id: 1, value: 22, label: "1" },
		        { id: 2, value: 23, label: "2" },
		        {label: "3" },
		        {label: "4" },
		        {label: "5" },
		      ],
		      ystart: 21,
		      yend: 35,
		      ystep: 3,
		      yaxis_tem: ".00",
		      target: 29.5,
		      target_color: "#0100FF",
		      plot: 15,
		    },
		    {
		      title: "Ebit on sale",
		      values: [
		        { id: 1, value: 6, label: "1" },
		        { id: 2, value: 6, label: "2" },
		        { id: 3, value: 5, label: "3" },
		        { id: 4, value: 4, label: "4" },
		        { id: 5, value: 3, label: "5" },
		      ],
		      ystart: 0,
		      yend: 7,
		      ystep: 2,
		      yaxis_tem: "%",
		      target: 6.5,
		      target_color: "#1DDB16",
		      plot: 15,
		    },
		    {
		      title: "Deep debt (k currency)",
		      values: [
		        { id: 1, value: 8000, label: "1" },
		        { id: 2, value: 7900, label: "2" },
		        { id: 3, value: 7800, label: "3" },
		        { id: 4, value: 7600, label: "4" },
		        { id: 5, value: 7500, label: "5" },
		      ],
		      ystart: 0,
		      yend: 12000,
		      ystep: 3000,
		      target: 10000,
		      target_color: "#FFBB00",
		      plot: 15,
		    },
		    {
		      title: "NPV (k currency)",
		      values: [
		        { id: 1, value: 4000, label: "1" },
		        { id: 2, value: 4200, label: "2" },
		        { id: 3, value: 4500, label: "3" },
		        { id: 4, value: 4800, label: "4" },
		        { id: 5, value: 5000, label: "5" },
		      ],
		      ystart: 0,
		      yend: 6000,
		      ystep: 2000,
		      target: 4500,
		      target_color: "#5F00FF",
		      plot: 15,
		    },
		  ],
		};