/* 
type
  label => 일반적인 text
  text => text 타입의 input
  number => number 타입의 input
  blank => child가 비어있는 td
  none => td조차 생성되지 않는다. rowspan, colspan에 의한 index 를 맞추기 위함
  result => 계산된 값을 출력하기 위한 type

colspan, rowspan => colspan, rowspan 값

text => type이 label일때 label의 값

id => element에 id 값을 부여. id값은 [id값]_[row값]_[column값] 형식으로 부여된다.

classnames => 배열형식으로 각 element에 class를 부여한다.

*/

const rows = [
  [
    {
      type: "label",
      colspan: 2,
      text: "% of carry over components",
    },
    { type: "text" },
    { type: "blank" },
    { type: "text" },
    { type: "blank" },
    { type: "text" },
    { type: "blank" },
    { type: "text" },
    { type: "blank" },
    { type: "text" },
    { type: "blank" },
    { type: "text" },
    { type: "blank" },
    { type: "text" },
    { type: "blank" },
  ],
  [
    {
      type: "label",
      colspan: 2,
      text: "DFMEA # of RPN ³ 100",
    },
    { type: "text" },
    { type: "blank" },
    { type: "text" },
    { type: "blank" },
    { type: "text" },
    { type: "blank" },
    { type: "text" },
    { type: "blank" },
    { type: "text" },
    { type: "blank" },
    { type: "text" },
    { type: "blank" },
    { type: "text" },
    { type: "blank" },
  ],
  [
    {
      type: "label",
      text: "Proto.",
    },
    {
      type: "label",
      text: "# of prototypes delivered",
    },
    { type: "number", id: "target" },
    { type: "blank" },
    { type: "number", id: "target" },
    { type: "blank" },
    { type: "number", id: "target" },
    { type: "blank" },
    { type: "number", id: "target" },
    { type: "blank" },
    { type: "number", id: "target" },
    { type: "blank" },
    { type: "number", id: "target" },
    { type: "blank" },
    { type: "number", id: "target" },
    { type: "blank" },
  ],
  [
    {
      type: "label",
      text: "conform.",
      rowspan: 3,
    },
    {
      type: "label",
      text: "On time delivery",
    },
    { type: "number", id: "source" },
    { type: "result" },
    { type: "number", id: "source" },
    { type: "result" },
    { type: "number", id: "source" },
    { type: "result" },
    { type: "number", id: "source" },
    { type: "result" },
    { type: "number", id: "source" },
    { type: "result" },
    { type: "number", id: "source" },
    { type: "result" },
    { type: "number", id: "source" },
    { type: "result" },
  ],
  [
    { type: "none" },
    {
      type: "label",
      text: "Customer claim",
    },
    { type: "number", id: "source" },
    { type: "result" },
    { type: "number", id: "source" },
    { type: "result" },
    { type: "number", id: "source" },
    { type: "result" },
    { type: "number", id: "source" },
    { type: "result" },
    { type: "number", id: "source" },
    { type: "result" },
    { type: "number", id: "source" },
    { type: "result" },
    { type: "number", id: "source" },
    { type: "result" },
  ],
  [
    { type: "none" },
    {
      type: "label",
      text: "# of prototypes non compliant",
    },
    { type: "number" },
    { type: "blank" },
    { type: "number" },
    { type: "blank" },
    { type: "number" },
    { type: "blank" },
    { type: "number" },
    { type: "blank" },
    { type: "number" },
    { type: "blank" },
    { type: "number" },
    { type: "blank" },
    { type: "number" },
    { type: "blank" },
  ],
  [
    {
      type: "label",
      colspan: 2,
      text: "proto effectiveness ID 9310",
    },
    { type: "text" },
    { type: "blank" },
    { type: "text" },
    { type: "blank" },
    { type: "text" },
    { type: "blank" },
    { type: "text" },
    { type: "blank" },
    { type: "text" },
    { type: "blank" },
    { type: "text" },
    { type: "blank" },
    { type: "text" },
    { type: "blank" },
  ],
  [
    {
      type: "label",
      colspan: 16,
      text:
        "proto effectiveness =  Nb of non compliant prototypes (fully equipped) / Nb of delivered prototypes",
    },
  ],
  [
    {
      type: "label",
      text: "DVP&R",
      rowspan: 4,
    },
    {
      type: "label",
      text: "Nb tests scheduled",
    },
    { type: "number", id: "target" },
    { type: "blank" },
    { type: "number", id: "target" },
    { type: "blank" },
    { type: "number", id: "target" },
    { type: "blank" },
    { type: "number", id: "target" },
    { type: "blank" },
    { type: "number", id: "target" },
    { type: "blank" },
    { type: "number", id: "target" },
    { type: "blank" },
    { type: "number", id: "target" },
    { type: "blank" },
  ],
  [
    { type: "none" },
    {
      type: "label",
      text: "Nb tests completed - passed",
    },
    { type: "number", id: "source" },
    { type: "result" },
    { type: "number", id: "source" },
    { type: "result" },
    { type: "number", id: "source" },
    { type: "result" },
    { type: "number", id: "source" },
    { type: "result" },
    { type: "number", id: "source" },
    { type: "result" },
    { type: "number", id: "source" },
    { type: "result" },
    { type: "number", id: "source" },
    { type: "result" },
  ],
  [
    { type: "none" },
    {
      type: "label",
      text: "Nb tests completed - failed",
    },
    { type: "number", id: "source" },
    { type: "result" },
    { type: "number", id: "source" },
    { type: "result" },
    { type: "number", id: "source" },
    { type: "result" },
    { type: "number", id: "source" },
    { type: "result" },
    { type: "number", id: "source" },
    { type: "result" },
    { type: "number", id: "source" },
    { type: "result" },
    { type: "number", id: "source" },
    { type: "result" },
  ],
  [
    { type: "none" },
    {
      type: "label",
      text: "Nb tests completed - on going",
    },
    { type: "number", id: "source" },
    { type: "result" },
    { type: "number", id: "source" },
    { type: "result" },
    { type: "number", id: "source" },
    { type: "result" },
    { type: "number", id: "source" },
    { type: "result" },
    { type: "number", id: "source" },
    { type: "result" },
    { type: "number", id: "source" },
    { type: "result" },
    { type: "number", id: "source" },
    { type: "result", classnames: ["test", "ttete"] },
  ],
];
